services:
  - type: web
    name: album-player
    runtime: docker
    branch: main
    plan: starter
    autoDeploy: true

    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /ping

    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xms128m -Xmx512m -XX:+UseSerialGC
      - key: JAVA_VERSION
        value: "21"
