services:
  - type: web
    name: album-player
    env: java
    plan: free
    buildCommand: "mvn clean install -DskipTests"
    startCommand: "java -jar target/album-player-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
